### ISSUE TITLE
More control over single/multicolumn mode

### ISSUE THREAD

**Issue by jeetsukumaran** [rhysd/committia.vim#10]
(1) Is there a way to manually toggle between single/multicolumn mode? E.g., when the Vim window first opens up, it might be narrow, but I might later expand the Vim window and then would like to switch to multicolumn mode. Or vice versa.

(2) Is there a way to force committia to open in one one mode or the other, regardless of the width of the window?

**Comment by rhysd** [comment]
> Is there a way to manually toggle between single/multicolumn mode?

Now it is not possible.

>  Is there a way to force committia to open in one one mode or the other, regardless of the width of the window?

Please set `'always'` to `g:committia_use_singlecolumn`.
