### ISSUE TITLE
support MERGE_MSG

### ISSUE THREAD

**Issue by davidosomething** [rhysd/committia.vim#21]
i am currently using on open MERGE_MSG via

```
autocmd dkocommittia
      \ BufNewFile,BufReadPost **/{MERGE_,TAG_EDIT,}MSG
      \ call committia#open('git')
```

It opens successfully but does not close committia on `:wq`/`ZZ`

**Comment by rhysd** [comment]
Hm, I'll try the config.  I want to add support for merge commits :smile:

**Comment by rhysd** [comment]
@davidosomething 

I enabled commitia.vim on merging commits.  Could you check the behavior?  Please do not forget removing your own config in .vimrc.

**Comment by davidosomething** [comment]
perfect! :clap:
