### ISSUE TITLE
Errors / Crash

### ISSUE THREAD

**Issue by Blue-Dog-Archolite** [rhysd/committia.vim#23]
after running `git merge development` or any branch

`"~/dev/flight/.git/MERGE_MSG" 7L, 292C
Error detected while processing function committia#open..<SNR>162_open_multicolumn..<SNR>162_open_status_window..<SNR>162_open_window..committia#git#status:
line    8:
E605: Exception not caught: committia: git: Failed to execute status command: fatal: The empty string is not a valid path^@
Error detected while processing function committia#open:
line   14:
E171: Missing :endif
Press ENTER or type command to continue
`

What can I do to help debug. I love this plugin.

**Comment by rhysd** [comment]
It looks bug of git.

Can you update git to latest and try again?

**Comment by Blue-Dog-Archolite** [comment]
yep. Looks like that did it. Thanks. Fedora's git is stuck at 2.5.x
