### ISSUE TITLE
committia doesn't overwrite user-supplied textwidth

### ISSUE THREAD

**Issue by xiongchiamiov** [rhysd/committia.vim#25]
I have `textwidth` specified in my `.vimrc` for normal operation.  However, I'd like committia to set the textwidth appropriately to 72 characters (or whatever it is, I forget) when I'm editing a commit message.  Is there a way to do this?

You can see my entire vimrc [here](https://github.com/xiongchiamiov/config/blob/master/.vimrc) in case it should already be working that way and it's something with my setup that's wonky.

**Comment by rhysd** [comment]
committia.vim never change `textwidth`.  So you can set it with general way.  If you want to set `textwidth` only in Git commit buffer, please try below:

```vim
autocmd FileType gitcommit setlocal textwidth=72
```

**Comment by xiongchiamiov** [comment]
Thanks, that works just fine.  I swore it used to wrap at 72 before I set textwidth, though... oh well, doesn't matter.
