### ISSUE TITLE
Error after updating commitia

### ISSUE THREAD

**Issue by ffesseler** [rhysd/committia.vim#32]
commitia worked fine until I updated the plugin yesterday.
When I type "git commit", I get an error : 

```
Error detected while processing function committia#open[14]..<SNR>81_open_multicolumn[10]..<SNR>81_open_status_window[1]..<SNR>81_open_window[1]..committia#git#status:
line   18:
E605: Exception not caught: committia: git: Failed to execute status command: fatal: This operation must be run in a work tree^@
Error detected while processing function committia#open:
line   14:
E171: Missing :endif
```

This seems related to the changes introduced with #31 .

**Comment by rhysd** [comment]
I'm always using HEAD of committia.vim but I've not seen this problem. Could you provide how to reproduce? And please let me know the version of `git`.

**Comment by ffesseler** [comment]
I'm using git version 2.10.1 (Apple Git-78)

I'll try to find how to reproduce it. Right now, it happens on a private git repo.

**Comment by rhysd** [comment]
`git status` command looks failed.

```diff
diff --git a/autoload/committia/git.vim b/autoload/committia/git.vim
index 0f92c53..19dce13 100644
--- a/autoload/committia/git.vim
+++ b/autoload/committia/git.vim
@@ -62,7 +62,9 @@ function! s:search_git_dir_and_work_tree() abort
 endfunction
 
 function! s:execute_git(cmd, git_dir, work_tree) abort
-    return s:system(printf('%s --git-dir="%s" --work-tree="%s" %s', g:committia#git#cmd, a:git_dir, a:work_tree, a:cmd))
+    let tmp = printf('%s --git-dir="%s" --work-tree="%s" %s', g:committia#git#cmd, a:git_dir, a:work_tree, a:cmd)
+    echom tmp
+    return s:system()
 endfunction
 
 function! s:ensure_index_file(git_dir) abort
```

With this diff, you can see actual command which was executed with `:message`. Could you try this and try the same command in command line? Does it fail also?

**Comment by rhysd** [comment]
If your repository is public, I think I can also try the situation.

**Comment by rhysd** [comment]
ping @anekos: if you notice something, please help me to fix this.

**Comment by ffesseler** [comment]
Command executed : 
```
git --git-dir="/Users/ffesseler/bla/.git" --work-tree="/Users/ffesseler/bla^@" diff -u --cached --no-color --no-ext-diff
```
It works fine when using it in the command line. Here is the output : 
```
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: server/client-html/src/main/resources/client-html-src/src/app/components/editors/noteEditor/noteEditor.js
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ noteEditor.js:1 @
//
import { NoteToolSet } from 'domain/model';
import { toHexa } from 'utils/color';
import { NotePaddings, NoteExtraTextPadding, NoteFont, TextCommonStyle } from 'domain/constants';
```

**Comment by rhysd** [comment]
```
/Users/ffesseler/bla^@
```

Ah, it looks that NL remains in work tree directory path... I'll take a look.

**Comment by ffesseler** [comment]
Wait, this is the command that actually fails : 
```
git --git-dir="/Users/ffesseler/bla/.git" --work-tree="/Users/ffesseler/bla^@" -c color.status=false status -b
```

**Comment by rhysd** [comment]
Thanks.

**Comment by rhysd** [comment]
I still can't understand what happens...

Could you try below diff? Something is ouput? If so, please let me see what was output.

```diff
diff --git a/autoload/committia/git.vim b/autoload/committia/git.vim
index 0f92c53..c482c57 100644
--- a/autoload/committia/git.vim
+++ b/autoload/committia/git.vim
@@ -43,6 +43,7 @@ function! s:search_git_dir_and_work_tree() abort
             let work_tree = fnamemodify(readfile(git_dir . '/gitdir')[0], ':h')
         else
             let work_tree = s:extract_first_line(s:system(printf('%s --git-dir="%s" rev-parse --show-toplevel', g:committia#git#cmd, git_dir)))
+            echom work_tree
         endif
         return [git_dir, work_tree]
     endif
```

**Comment by ffesseler** [comment]
Here is the output
```
/Users/ffesseler/bla^@
/Users/ffesseler/bla^@
```

**Comment by rhysd** [comment]
The `^@` represetns newline. So, actual command is:

```
git --git-dir="/Users/ffesseler/bla/.git" --work-tree="/Users/ffesseler/bla
" -c color.status=false status -b
```

I think it also fails in command line (if you try, please enter new line after ctrl+v in terminal)

**Comment by rhysd** [comment]
@ffesseler Thank you. So I guess

```vim
let work_tree = s:extract_first_line(s:system(printf('%s --git-dir="%s" rev-parse --show-toplevel', g:committia#git#cmd, git_dir)))
```

returns the wrong work tree path.

**Comment by ffesseler** [comment]
Indeed: 
```git --git-dir="/Users/ffesseler/bla/.git" --work-tree="/Users/ffesseler/bla" -c color.status=false status -b```
works in command line
```
git --git-dir="/Users/ffesseler/bla/.git" --work-tree="/Users/ffesseler/bla^@" -c color.status=false status -b
``` does not.

**Comment by rhysd** [comment]
Could you tell me the output of

```
:echo &magic
```

It changes how to interpret regex in `match()` in `s:extract_first_line()`.

**Comment by rhysd** [comment]
@ffesseler Thank you for clarifying it. The newline `^@` looks root cause of this bug.

**Comment by ffesseler** [comment]
:echo &magic outputs 1

**Comment by rhysd** [comment]
Thanks. So `nomagic` is not related to this problem.

I submitted a commit 08b761a . Your system is macOS. So it may not be related to this problem, but could you try the latest?

**Comment by rhysd** [comment]
And if you can, please tell me the output of below command:

```
:echom string(system("git --git-dir='/Users/ffesseler/bla/.git' rev-parse --show-toplevel"))
```

**Comment by ffesseler** [comment]
Same issue with the last version.
```
:echom string(system("git --git-dir='/Users/ffesseler/bla/.git' rev-parse --show-toplevel"))
```
outputs : 
'/Users/ffesseler/bla^@'

**Comment by rhysd** [comment]
Does 3be483f fix this problem?

**Comment by ffesseler** [comment]
Yes ! Works fine now :)

**Comment by rhysd** [comment]
I found that `[^\n]\+` should have been `^[^\n]\+`, but 3be483f also works. Thank you for your cooperation. It was very helpful 👍

**Comment by ffesseler** [comment]
Thanks to you for fixing this very quickly and for providing me some tips to help debugging !
