### ISSUE TITLE
Both images in the readme are broken

### ISSUE THREAD

**Issue by zacps** [rhysd/committia.vim#34]
[One](https://camo.githubusercontent.com/6d92a44bbace7c73141e6fa5a7a0c4b68713517d/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f323735333133382f73637265656e73686f745f636f6d6d69747469612e6a7067)
[Two](https://camo.githubusercontent.com/829856abefb4111697c255c1e4d314fde08b389f/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f323735333133382f73637265656e73686f745f636f6d6d69747469615f6e6172726f772e6a7067)

**Comment by rhysd** [comment]
Thank you for catching that. I guess it's because Dropbox stops public directories...

**Comment by zacps** [comment]
It's a githubusercontent link though, dropbox shouldn't have anything to do with it, should it?

**Comment by rhysd** [comment]
githubusercontent is a cache URL and it is regularly expired. I think you can see README.md raw source. The links are for dropbox.com.

**Comment by zacps** [comment]
Huh, it's also used for raw uploads (if you drop an image into an issue for
example.)
