### ISSUE TITLE
All files are shown as deleted

### ISSUE THREAD

**Issue by xaizek** [rhysd/committia.vim#39]
How to reproduce:
1. `git clone https://github.com/vifm/vifm.git`
2. `cd vifm`
3. `echo a >> AUTHORS`
4. `git commit -a`

I suspect that worktree was determined incorrectly, this would explain the effect.

**Comment by rhysd** [comment]
I could not reproduce. I tried the sequence, but output is as follow:

```
# Changes to be committed:
#	modified:   AUTHORS
```

It looks to work for me. I guess there are more preconditions for reproducing this.

**Comment by xaizek** [comment]
Yes, it seems to not be repository specific. Not sure how I concluded otherwise initially. Try adding this to `vimrc`:
```vim
autocmd BufReadPost * lchdir %:p:h
```
The problem seems to be that command:
```bash
git --git-dir=$PWD rev-parse --show-toplevel
```
run inside `.git` directory returns path to git directory and not to worktree.

**Comment by rhysd** [comment]
Thank you for additional information in spite of long blank after this issue was created. Yeah, I think the `:lchdir` causes this issue. I need to investigate whether this issue is fixable.

**Comment by rhysd** [comment]
@xaizek I tried to cover this usecase at 0f57324. Could you try the latest?

**Comment by xaizek** [comment]
0f57324f9228c85c8c8bf83745bd166bd1346ba7 works fine for me, thank you!
