### ISSUE TITLE
Initial merge message is dropped

### ISSUE THREAD

**Issue by xaizek** [rhysd/committia.vim#41]
Git provides first line for a merge message saying `Merge branch 'branch-name-here'`. In addition to that invoking `git merge` with `--log=999999` argument adds list of commits that are being merged into destination branch. 

committia doesn't preserve this information. Is there a way to keep it? It pretty much needs to work for merges the same was as it already does for `git commit --amend`.

**Comment by rhysd** [comment]
@xaizek Could you please check the latest?

**Comment by xaizek** [comment]
Works as expected, thanks!
