### ISSUE TITLE
git commit -a not working properly for diff view

### ISSUE THREAD

**Issue by PlasmaHH** [rhysd/committia.vim#48]
Due to committia using --cached for the git diff command when doing a commit -a there is no diff result that will be displayed. Ideally committia should parse the text in the COMMIT_EDITMSG to figure out the files. Due to git using multiple languages it should probably have some way to configure what to look for, best is probably # <changed text in whatever language>:      <filename> and then have a list of possible words there.

**Comment by xaizek** [comment]
I have latest committia.vim and git 2.14.5. I often do `git commit -a` and see diff, tried it just now and it's there.

**Comment by PlasmaHH** [comment]
Are all files in the diff, or only those previously added via `git add` ?
Change just one file, don't `git add` and do a `git diff -u --cached --no-color --no-ext-diff` (the command that is run by committia). For me (git 2.20.1) this does not show any output. Also from the git manual:

```
 git diff [<options>] --cached [<commit>] [--] [<path>...]
           This form is to view the changes you staged for the next commit relative to the named <commit>. …

```

**Comment by xaizek** [comment]
> Are all files in the diff, or only those previously added via `git add`?

All files.

Running `git diff -u --cached` before the commit and during the commit produces different results. If I do `:!cd .. && git diff -u --cached --no-color --no-ext-diff` while inside Vim to provide commit message, I see the diff. I guess it's because there are a bunch of `$GIT_*` environment variables setup in the editor by the `git` process.

**Comment by PlasmaHH** [comment]
Okay, so for whatever reason they must have gotton lost in my case then I guess? Do you happen to know which ones are necessary so I can manually set, try and verify?

**Comment by rhysd** [comment]
@PlasmaHH Could you show the steps to reproduce from `git init`? I think we should confirm reproduction at first.

e.g.

```
mkdir foo && cd foo
echo "foo\nbar" > test.txt
git init .
git add test.txt -m 'first'
echo "aaa" >> test.txt
git add test.txt
git add test.txt -a
```

**Comment by PlasmaHH** [comment]
@rhysd I guess you mean add test.txt and then commit -m and in the last line no add but commit.

I am trying to "negatively" reproduce this, the hint by xaizek about the environment seems plausible, when I can figure out what value to look for, set it and it works then, I can rule out this plugin and have to search for whatever is blocking that variable from getting through

**Comment by xaizek** [comment]
I can tell you which ones I have set inside the editor:
* `GIT_DIR`
* `GIT_AUTHOR_DATE`
* `GIT_INDEX_FILE`
* `GIT_AUTHOR_NAME`
* `GIT_PREFIX`
* `GIT_AUTHOR_EMAIL`

The most important one seems to be `GIT_INDEX_FILE` as it points to `.../.git/index.lock`, which seems to be the index file with all changes staged. I confirmed that by re-exporting `GIT_INDEX_FILE` in a separate terminal while editor is spawn for commit and doing `git diff --cached`, it shows previously unstaged changes.

**Comment by PlasmaHH** [comment]
Indeed that variable is missing, setting it will return to the expected behaviour. I will have to figure out why that variable went missing, probably one too many plugins messing with things... 

Thanks for your time

**Comment by rhysd** [comment]
@xaizek Thank you for the support.

**Comment by xaizek** [comment]
@rhysd, my pleasure, I was surprised that something I regularly use supposedly can't work at all.
