### ISSUE TITLE
How to trigger the committia

### ISSUE THREAD

**Issue by LintaoAmons** [rhysd/committia.vim#62]
Hi friend~

I saw in README that type `git commit` will show the commit buffer?

But seems I can't. And I also tried `:Commit<CR>`

I also see there's `<Plug>` to map to a shortcut, but seem there's no one to map to trigger the commit buffer?

**Comment by rhysd** [comment]
To trigger it manually, run `:call committia#open('git')` in `COMMIT_EDITMSG` buffer. You can define your own command if you want as well.
