### ISSUE TITLE
In windows some command about git cannot work

### ISSUE THREAD

**Issue by Freed-Wu** [rhysd/committia.vim#66]
```
/usr/bin/zsh: can''t open input files: /s
```

I found it is because
some command like

```
systemlist('git ls-files -m 2>/dev/null')
```

Environment: Windows msys2's nvim 0.10.0

**Comment by rhysd** [comment]
It may not work. I haven't used MSYS2 so I'm not understanding what is the root cause here.

**Comment by xaizek** [comment]
`/s` looks like a parameter of `cmd.exe` which gets passed to `zsh`.  It could come from `'shellcmdflag'`.  This might be unrelated to the plugin.

**Comment by rhysd** [comment]
Thanks @xaizek for the point.

It sounds like a problem around shell configuration. You may need to adjust `'shell'`, `'shellcmdflag'`, ... options for your environment in your init.lua.

**Comment by Freed-Wu** [comment]
That is msys2's neovim `set shell=$SHELL` (zsh), however it still use `set shellcmdflags=/c`, not `-c`.
